export const metadata = {
  title: "中铁六局",
  description: "Generated by create next app",
}

export default function Home() {
  return (
    <main>
      123
      <i className="iconfont icon-duanxinguanli"></i>
    </main>
  )
}
