import dynamic from "next/dynamic"

export const metadata = {
  title: "首页-平台端",
  description: "Generated by create next app",
}

const HomePage = dynamic(() => import("@/components/HomePage"), { ssr: false })
export default function home() {
  return <HomePage />
}

//
